spring:
  rabbitmq:
    host: 111.231.252.55
    username: admin
    password: 123456
    port: 5672
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
