spring:
  application:
    name: configclient
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
    config:
      discovery:
        enabled: true
        service-id: configserver
